// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxu-Qur7igH-j4DiEYJgrau4e3QZVYHug',
    appId: '1:441616463630:web:b488cdace6b81623ee095f',
    messagingSenderId: '441616463630',
    projectId: 'myapp-ddda6',
    authDomain: 'myapp-ddda6.firebaseapp.com',
    storageBucket: 'myapp-ddda6.firebasestorage.app',
    measurementId: 'G-8TFHZJJCQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYo_a_tFaU0zBEMQScao5rsZefJ7fFepo',
    appId: '1:441616463630:android:cf64f36bfe0cee7bee095f',
    messagingSenderId: '441616463630',
    projectId: 'myapp-ddda6',
    storageBucket: 'myapp-ddda6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaApRKOVUVqZOB4ncsNJ5vg8mSycddBhw',
    appId: '1:441616463630:ios:b19616f2a57b22fbee095f',
    messagingSenderId: '441616463630',
    projectId: 'myapp-ddda6',
    storageBucket: 'myapp-ddda6.firebasestorage.app',
    androidClientId: '441616463630-94vsjb3en25vbrqpa9gmb4ii7bko3g8v.apps.googleusercontent.com',
    iosClientId: '441616463630-4b9ttlss8huvdap1n190nm45vn3i8s1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminpanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaApRKOVUVqZOB4ncsNJ5vg8mSycddBhw',
    appId: '1:441616463630:ios:b19616f2a57b22fbee095f',
    messagingSenderId: '441616463630',
    projectId: 'myapp-ddda6',
    storageBucket: 'myapp-ddda6.firebasestorage.app',
    androidClientId: '441616463630-94vsjb3en25vbrqpa9gmb4ii7bko3g8v.apps.googleusercontent.com',
    iosClientId: '441616463630-4b9ttlss8huvdap1n190nm45vn3i8s1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminpanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxu-Qur7igH-j4DiEYJgrau4e3QZVYHug',
    appId: '1:441616463630:web:9b94864e3569da95ee095f',
    messagingSenderId: '441616463630',
    projectId: 'myapp-ddda6',
    authDomain: 'myapp-ddda6.firebaseapp.com',
    storageBucket: 'myapp-ddda6.firebasestorage.app',
    measurementId: 'G-QFFHJHYX8T',
  );
}
